
SCHOOL_CHOICES = [

    ('abu', 'Ahmadu Bello University'),
    ('abuad', 'Afe Babalola University'),
    ('aaua', 'Adekunle Ajasin University'),
    ('aau', 'Ambrose Alli University'),
    ('au', 'Anchor University'),
    ('bells', 'Bells University of Technology'),
    ('bu', 'Bingham University'),
    ('bsu', 'Benue State University'),
    ('covenant', 'Covenant University'),
    ('delsu', 'Delta State University'),
    ('eksu', 'Ekiti State University'),
    ('fubk', 'Federal University, Birnin Kebbi'),
    ('fud', 'Federal University, Dutse'),
    ('fudm', 'Federal University, Dutsin-Ma'),
    ('fuk', 'Federal University, Kashere'),
    ('ful', 'Federal University, Lokoja'),
    ('fum', 'Federal University, Maritse'),
    ('futminna', 'Federal University of Technology, Minna'),
    ('futo', 'Federal University of Technology, Owerri'),
    ('fuwukari', 'Federal University, Wukari'),
    ('fuoye', 'Federal University, Oye-Ekiti'),
    ('funai', 'Federal University, Ndufu-Alike'),
    ('fuotuoke', 'Federal University, Otuoke'),
    ('imsu', 'Imo State University'),
    ('kwara', 'Kwara State University'),
    ('lasu', 'Lagos State University'),
    ('lautech', 'Ladoke Akintola University of Technology'),
    ('mouau', 'Michael Okpara University of Agriculture, Umudike'),
    ('noun', 'National Open University of Nigeria'),
    ('ndu', 'Niger Delta University'),
    ('nile', 'Nile University'),
    ('oau', 'Obafemi Awolowo University'),
    ('osustech', 'Ondo State University of Science and Technology'),
    ('osun', 'Osun State University'),
    ('pausti', 'Plateau State University'),
    ('rsust', 'Rivers State University'),
    ('tasued', 'Tai Solarin University of Education'),
    ('ui', 'University of Ibadan'),
    ('unilag', 'University of Lagos'),
    ('uniosun', 'Osun State University'),
    ('uniabuja', 'University of Abuja'),
    ('uniben', 'University of Benin'),
    ('unical', 'University of Calabar'),
    ('unijos', 'University of Jos'),
    ('unilori', 'University of Ilorin'),
    ('unimaid', 'University of Maiduguri'),
    ('unimkar', 'University of Mkar'),
    ('unn', 'University of Nigeria, Nsukka'),
    ('ibbul','ibrahim badamasi babangida Unniversity Lapai'),

]
